mongodb:
  host: 127.0.0.1
  port: 27017
  db: astraflux
  username: scheduleAdmin
  password: scheduleAdminPassword

redis:
  host: 127.0.0.1
  port: 6379
  password: scheduleAdminPassword
  db_index: 8

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: scheduleAdmin
  password: scheduleAdminPassword

logger:
  path: logs
  level: INFO

web:
  port: 7860
  username: scheduleAdmin
  password: scheduleAdminPassword

openai:
  temporary_directory: temporary_directory
  expand_skill_directory: skill

  openclaw:
    server: http://127.0.0.1:18789
    sessionKey: x-session
    token: fdab5ad1568d556d5f81ff5252d09cbca10fa6736af84b56

  modelApi:
    server: http://192.168.208.1:1234/v1
    name: qwen/qwen3.5-9b
    apiKey: sk-lm-eMrfKTYy:bB4kywtBdPBwOMbMjs6r
